---
abstract: 'verify solutions for solitaire games.'
author:
  - 'Shlomi Fish <shlomif@cpan.org>'
build_requires:
  File::Spec: '0'
  File::Temp: '0'
  IO::Handle: '0'
  IPC::Open3: '0'
  Module::Build: '0.28'
  Test::Differences: '0'
  Test::More: '0'
  base: '0'
configure_requires:
  Module::Build: '0.28'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.020, CPAN::Meta::Converter version 2.142060'
license: mit
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Games-Solitaire-Verify
requires:
  Class::XSAccessor: '0'
  Data::Dumper: '0'
  Exception::Class: '0'
  Getopt::Long: '2.36'
  List::MoreUtils: '0'
  List::Util: '0'
  MooX::late: '0.010'
  POSIX: '0'
  autodie: '0'
  parent: '0'
  perl: '5.008'
  strict: '0'
  vars: '0'
  warnings: '0'
resources:
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=Games-Solitaire-Verify
  repository: http://bitbucket.org/shlomif/fc-solve
version: '0.1400'
