---
abstract: 'verify solutions for solitaire games.'
author:
  - 'Shlomi Fish <shlomif@iglu.org.il>'
build_requires:
  Test::More: 0
  autodie: 0
configure_requires:
  Module::Build: 0.36
dynamic_config: 1
generated_by: 'Module::Build version 0.4005, CPAN::Meta::Converter version 2.131560'
keywords:
  - "baker's dozen"
  - "baker's game"
  - card
  - 'card games'
  - cards
  - 'eight off'
  - forecell
  - foundations
  - freecell
  - french
  - games
  - moves
  - patience
  - seahaven
  - 'seahaven towers'
  - 'simple simon'
  - single-player
  - solitaire
  - solutions
  - solve
  - solving
  - verification
  - verify
license: mit
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Games-Solitaire-Verify
provides:
  Games::Solitaire::Verify:
    file: lib/Games/Solitaire/Verify.pm
    version: 0.1200
  Games::Solitaire::Verify::App::CmdLine:
    file: lib/Games/Solitaire/Verify/App/CmdLine.pm
  Games::Solitaire::Verify::App::CmdLine::Expand:
    file: lib/Games/Solitaire/Verify/App/CmdLine/Expand.pm
  Games::Solitaire::Verify::Base:
    file: lib/Games/Solitaire/Verify/Base.pm
    version: 0.1200
  Games::Solitaire::Verify::Card:
    file: lib/Games/Solitaire/Verify/Card.pm
    version: 0.1200
  Games::Solitaire::Verify::Column:
    file: lib/Games/Solitaire/Verify/Column.pm
    version: 0.1200
  Games::Solitaire::Verify::Exception:
    file: lib/Games/Solitaire/Verify/Exception.pm
    version: 0.1200
  Games::Solitaire::Verify::Foundations:
    file: lib/Games/Solitaire/Verify/Foundations.pm
    version: 0.1200
  Games::Solitaire::Verify::Freecells:
    file: lib/Games/Solitaire/Verify/Freecells.pm
    version: 0.1200
  Games::Solitaire::Verify::KlondikeTalon:
    file: lib/Games/Solitaire/Verify/KlondikeTalon.pm
    version: 0.1200
  Games::Solitaire::Verify::Move:
    file: lib/Games/Solitaire/Verify/Move.pm
    version: 0.1200
  Games::Solitaire::Verify::Solution:
    file: lib/Games/Solitaire/Verify/Solution.pm
    version: 0.1200
  Games::Solitaire::Verify::Solution::ExpandMultiCardMoves:
    file: lib/Games/Solitaire/Verify/Solution/ExpandMultiCardMoves.pm
    version: 0.1200
  Games::Solitaire::Verify::State:
    file: lib/Games/Solitaire/Verify/State.pm
    version: 0.1200
  Games::Solitaire::Verify::VariantParams:
    file: lib/Games/Solitaire/Verify/VariantParams.pm
    version: 0.1200
  Games::Solitaire::Verify::VariantsMap:
    file: lib/Games/Solitaire/Verify/VariantsMap.pm
    version: 0.1200
requires:
  Class::XSAccessor: 0
  Exception::Class: 0
  File::Spec: 0
  Getopt::Long: 2.36
  List::Util: 0
  base: 0
  strict: 0
  warnings: 0
resources:
  MailingList: http://tech.groups.yahoo.com/group/fc-solve-discuss/
  homepage: http://fc-solve.shlomifish.org/verify-code/
  license: http://www.opensource.org/licenses/mit-license.php
  repository: http://bitbucket.org/shlomif/fc-solve
version: 0.1200
